[package]
name = "weather-bot"
version = "0.1.0"
authors = ["smehlhoff"]
edition = "2018"

[dependencies]
chrono = "0.4.19"
reqwest = { version = "0.11.11", features = ["json"] }
serde = "1.0.137"
serde_derive = "1.0.137"
serde_json = "1.0.81"
serenity = "0.11.2"
timeago = "0.3.1"
tokio = { version = "1.19.2", features = ["full"] }