[package]
name = "weather-bot"
version = "0.1.0"
authors = ["smehlhoff"]
edition = "2018"

[dependencies]
chrono = "0.4.26"
reqwest = { version = "0.11.18", features = ["json"] }
serde = "1.0.167"
serde_derive = "1.0.167"
serde_json = "1.0.100"
serenity = "0.11.6"
timeago = "0.4.1"
tokio = { version = "1.29.1", features = ["full"] }