[package]
name = "weather-bot"
version = "0.1.0"
authors = ["smehlhoff"]
edition = "2018"

[dependencies]
chrono = "0.4.19"
reqwest = { version = "0.11", features = ["json"] }
serde = "1.0.126"
serde_derive = "1.0.126"
serde_json = "1.0.64"
serenity = "0.10"
timeago = "0.3.0"
tokio = { version = "1.0", features = ["full"] }